inputs:
  channel: demo
triggers:
  scheduled: []
  webhooks: []
steps:
  - text: "# Simple section"
    id: ""
    desc: ""
    inputs: {}
    action: ""
    name: ""
    runner_id: ""
    connections: {}
    when: ""
    timeout: 0
    goto: {}
  - text: >-
      ## How to start with Slack integration



      This playbook illustrate slack integration. 


      In order to sue it you need a slack connections configured


      Action below uses an input parameter as the slack channel to send the message to.  Do not forget to change its value in 'Input Parameters' tab


      The message itself uses pre defined context variables.
    id: ""
    desc: ""
    inputs: {}
    action: ""
    name: ""
    runner_id: ""
    connections: {}
    when: ""
    timeout: 0
    goto: {}
  - text: ""
    id: S1
    desc: Description
    inputs:
      Channel: "{{ inputs.channel }}"
      Text: "Hello from {{ username }} - Execution : {{ execution_id }} - Playbook :
        {{ playbook_name }} "
    action: slack.SendMessage
    name: Action
    runner_id: ""
    connections:
      slack: slack_connection
    when: ""
    timeout: 0
    goto: {}
name: hello_slack
tags: []
version: ""
active: false
connections:
  slack: slack_connection
runner_id: ""
outputs: {}
private_execution_environment_settings:
  ? kubernetes
counting_steps: 1
